[book]
authors = ["Mark Veltzer"]
language = "en"
src = "src"
title = "rsshell - A Unix Shell in Rust"

[build]
build-dir = "book"

[output.html]
default-theme = "rust"
preferred-dark-theme = "ayu"
git-repository-url = "https://github.com/veltzer/rsshell"
edit-url-template = "https://github.com/veltzer/rsshell/edit/master/docs/{path}"
